version: '3.8'

services:
  # Ollama service - AI model server
  ollama:
    image: ollama/ollama:latest
    container_name: englog-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - englog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # API service - EngLog application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: englog-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OLLAMA_SERVER_URL=http://ollama:11434
      - OLLAMA_MODEL_NAME=gemma3:1b
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - englog-network
    volumes:
      # Optional: Mount source code for development hot-reload
      # Uncomment the following line for development mode
      # - .:/app/src:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local

networks:
  englog-network:
    driver: bridge
